#!/bin/sh
#nat6更新脚本，在接口变动时会执行相应的命令

#获取nat6-helper插件的启用状态
enable=$(uci get nat6-helper.@nat6-helper[0].enabled)                                    #插件是否启用
WAN6_NAME=$(uci get nat6-helper.@nat6-helper[0].name)                                    #选定的IPv6上行接口，默认为wan6

#若变动网卡不是插件内设置的IPv6上行接口则直接退出
[ "$INTERFACE" = "$WAN6_NAME" ] || exit 0

#网络变化时候的动作
if [ "$ACTION" = ifup -o "$ACTION" = ifupdate ];then
    /etc/init.d/nat6-helper stop_nat6
    /etc/init.d/nat6-helper start_nat6

#接口断开时候的动作
elif [ "$ACTION" = ifdown ]; then
    /etc/init.d/nat6-helper stop_nat6
fi
