#!/bin/sh
#nat6转发规则守护脚本，在插件开启时候，防止因为防火墙重启而丢失防火墙的nat6转发

enable=$(uci get nat6-helper.@nat6-helper[0].enabled)                                    #插件是否启用

#插件未开启则退出
[ $enable = "0" ] && exit 0
#/etc/init.d/nat6-helper stop_nat6
#/etc/init.d/nat6-helper start_nat6
